### PR TITLE
Fix POSIX-compliance bugs i.e. no colors and etc

### LINKED ISSUE #5: Broken output with any shell
As the title says, the output is broken in any shell (sh, bash, and fish). Changing the shebang from sh to bash fixes the issue

Screenshots with sh shebang:
screen-171222-095915
screen-171222-100002
screen-171222-100042

Screenshot with bash shebang:
Screenshot_20221217-095339

### PR DESCRIPTION
**Pull request by WhoseTheNerd**
Fixes #5 

[Output](https://i.imgur.com/VSHPP5c.png)

### CODE REVIEW

**Comment by gentoo-btw** [comment]
but why i should use sh instead of bash? most fetches (e.g neofetch) use bash

**Comment by WhoseTheNerd** [comment]
Portability reasons. You would want your script to work in another system (i.e. busybox environment). Also sh is faster than bash due to less complexity (See bash vs dash).

**Comment by gentoo-btw** [comment]
> Portability reasons. You would want your script to work in another system (i.e. busybox environment). Also sh is faster than bash due to less complexity (See bash vs dash).

hmm.. I guess I will merge this pr. and shellcheck (revieedog) outputs "no matching files to check" maybe because ramfetch doesn't have the .sh file extension

**Comment by gentoo-btw** [comment]
oh, and I almost forgot, I have rename the "made with bash" badge to "made with sh"

**Pull request merged**
